service: aws-node-rest-api-project

frameworkVersion: '2'

plugins:
  - serverless-offline #serverless-offline needs to be last in the list

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /hello
          method: get
  foo:
    handler: src/foo.foo
    events:
      - http:
          path: /foo
          method: get
  bar:
    handler: src/foo.foo
    events:
      - http:
          path: /bara
          method: get
