service: serverless

frameworkVersion: '2'

plugins:
  - serverless-offline #serverless-offline needs to be last in the list

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  apiGateway:
    metrics: true
  logs:
    restApi: true

functions:
  customers.get:
    handler: src/handlers/customers/get.handler
    events:
      - http:
          path: /customers
          method: GET
  customers.getById:
    handler: src/handlers/customers/getById.handler
    events:
      - http:
          path: /customers/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  customers.create:
    handler: src/handlers/customers/create.handler
    events:
      - http:
          path: /customers
          method: POST
  customers.delete:
    handler: src/handlers/customers/delete.handler
    events:
      - http:
          path: /customers/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true
